Sentry.WebApp/ViewModels/GiftDisbursements/DisbursementCustomValidation.cs
using System.ComponentModel.DataAnnotations;

namespace Sentry.WebApp.ViewModels.GiftDisbursements
{
    public class CustomDebitAccountAllDigitsValidationAttribute : ValidationAttribute
    {
        public override bool IsValid(object value)
        {
            var debitAccount = (string)value;
            var test = debitAccount.Replace("-", "");
            foreach (char c in test)
            {
                if (!char.IsDigit(c))
                {
                    return false;
                }
            }
            return true;
        }
    }
        
}

Sentry.WebApp/ViewModels/GiftDisbursements/GiftDisbursementDashboard.cs
using Sentry.Domain.AccountsPayable.Entities;
using System.Collections;
using System.Collections.Generic;

namespace Sentry.WebApp.ViewModels.GiftDisbursements
{
    public class GiftDisbursementDashboard : BaseViewModel
    {
        public GiftDisbursementList AssociateVicePresidentDisbursements { get; set; }
        public GiftDisbursementList VicePresidentDisbursements { get; set; }
        public GiftDisbursementList CFODisbursements { get; set; }
        public GiftDisbursementList GeneralCounselDisbursements { get; set; }
        public GiftDisbursementList ApReviewerDisbursements { get; set; }
        public GiftDisbursementList ScholarshipDisbursements { get; set; }
        public GiftDisbursementList ApManagerDisbursements { get; set; }
    }
}

Sentry.WebApp/ViewModels/GiftDisbursements/GiftDisbursementsListViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Sentry.WebApp.ViewModels.GiftDisbursements
{
    public class GiftDisbursementsListItem
    {
        public string DateCreated { get; set; }
        public string FormNumber { get; set; }
        public string PreparedByName { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string ProjectId { get; set; }
        public string PayeeName { get; set; }
        public string PayeePaymentType { get; set; }
        public string PayeeSpecialInstructions { get; set; }
        public string Total { get; set; }
        public long GiftDisbursementId { get; set; }
        //public string Error { get; set; }
        public string ProcessingError { get; set; }
        public bool Rejected { get; set; }
        public string Fund { get; set; }
        public bool IsPending { get; set; }
        public string LastApprovedOnDate { get; set; }
        public decimal? Total1099 { get; set; }
        public bool Has1099TotalValue { get; set; }
        public string PendingComments { get; set; }
        public string APReviewerEmployeeId { get; set; }
        public string ReviewerNotes { get; set; }
        public bool PreviouslyRejected { get; set; }
        public bool PreviouslyApprovedByUser { get; set; }
        public IEnumerable<GiftDisbursementApprover> GiftDisbursementApprovalHistory { get; set; }
        public string RowStatusClass { get; set; }
        public bool Resubmitted { get; set; }

        public static explicit operator GiftDisbursementsListItem(Sentry.Domain.AccountsPayable.Entities.GiftDisbursement giftDisbursement)
        {
            string sLastApproved = String.Empty;
            var approvalHistory = giftDisbursement.GiftDisbursementApprovalHistory;

            if (giftDisbursement.LastApprovedOnDate.HasValue)
            { 
                var lastApprovedOnDate = (DateTime)giftDisbursement.LastApprovedOnDate;
                sLastApproved = lastApprovedOnDate.ToString("MM/dd/yyyy");
            }

            return new GiftDisbursementsListItem()
            {
                DateCreated = giftDisbursement.DateCreated.ToString("MM/dd/yyyy"),
                FormNumber = giftDisbursement.FormNumber,
                DepartmentCode = giftDisbursement.DepartmentCode,
                DepartmentName = giftDisbursement.DepartmentName,
                PayeeName = giftDisbursement.PayeeName,
                PayeePaymentType = giftDisbursement.PayeePaymentType,
                Fund = giftDisbursement.Fund,
                PayeeSpecialInstructions = giftDisbursement.PayeePaymentSpecialInstructions,
                Total = giftDisbursement.Total.ToString("C"),
                PreparedByName = $"{giftDisbursement.PreparedByFirstName} {giftDisbursement.PreparedByLastName}",
                GiftDisbursementId = giftDisbursement.Id,
                //Error = giftDisbursement.Error,
                ProcessingError = giftDisbursement.ProcessingError,
                Rejected = giftDisbursement.RejectedByEscalatedApprovers,
                IsPending = giftDisbursement.Pending,
                LastApprovedOnDate = sLastApproved,
                Total1099 = giftDisbursement.Total1099,
                Has1099TotalValue = (giftDisbursement.Total1099 > decimal.Zero ? true : false),
                PendingComments = giftDisbursement.PendingComments,
                ReviewerNotes = giftDisbursement.ReviewerNotes,
                APReviewerEmployeeId = giftDisbursement.APReviewerEmployeeId,
                PreviouslyRejected = giftDisbursement.PreviouslyRejected,
                PreviouslyApprovedByUser = giftDisbursement.PreviouslyApprovedByUser,
                Resubmitted = giftDisbursement.Resubmitted,
                GiftDisbursementApprovalHistory = (approvalHistory != null && approvalHistory.Any() ? approvalHistory.Select(h => (GiftDisbursementApprover)h) : Enumerable.Empty<GiftDisbursementApprover>())
            };
        }
    }

    public class GiftDisbursementsListViewModel : BaseIntegrationViewModel
    {
        public GiftDisbursementsListViewModel() : base()
        {

        }

        public string Organization { get; set; }
        public IEnumerable<GiftDisbursementsListItem> Disbursements { get; set; }
        public string ListType { get; set; }

    }    
}

Sentry.WebApp/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Sentry.WebApp.Data;
using Sentry.WebApp.Extensions;
using Sentry.WebApp.Services;
using Sentry.WebApp.ViewModels.GiftDisbursements;
using Sentry.WebApp.ViewModels.Invoices;
using Sentry.WebApp.ViewModels.SupportingDocuments;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Sentry.Domain.Forms.Entities;

namespace Sentry.WebApp.Controllers
{
    [ApiController]
    [Route("invoices")]
    [Authorize]
    public class InvoicesController : Controller
    {
        private readonly Config _config;
        private readonly IWebHostEnvironment _environment;
        private readonly string _invoicePdfPath;
        private readonly IDomainService _domainService;
        private readonly ILogger _logger;
        //private readonly IConfiguration _configuration;

        public InvoicesController(
            ILogger<InvoicesController> logger,
            //IConfiguration configuration,
            IDomainService domainService,
            IOptions<Config> config,
            INotificationService notificationService,
            IWebHostEnvironment environment)
        {
            _config = config.Value;
            _environment = environment;
            _invoicePdfPath = $"{environment.WebRootPath}\\invoice-pdfs";
            _domainService = domainService;
            _logger = logger;

        }

        [HttpGet("")]
        [AllowAnonymous]
        public IActionResult Index()
        {
            if (HttpContext.Request.Headers["X-API-KEY"] != _config.XAPIKey)
            {
                return Unauthorized();
            }
            return Ok("YOU HAVE BEEN AUTHORIZED TO ACCESS INVOICES");
        }

        private async Task<PDFViewModelSimplified> SetupViewModel(long id)
        {
            var form = await _domainService.AccountsPayableOperations.GetGiftDisbursement(id);
            var model = (PDFViewModelSimplified)form;
            try
            {
                var supportingDocuments = await _domainService.PaperSaveOperations.AdvancedSearchDocumentsByFormNumber(form.FormNumber);
                var docsModel = new SupportingDocumentsListViewModel();
                model.SupportingDocuments = supportingDocuments.Select(d => (SupportingDocument)d)
                    .Select(d => d.FileName);
                return model;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error getting supporting documents for {formNumber}", form.FormNumber);
                model.SupportingDocuments = Enumerable.Empty<string>();
                return model;
            }
        }

        private async Task<Sentry.Domain.PaperSave.Entities.NewDocument> CreatePDF(PDFViewModelSimplified model)
        {

            var fileName = $"{model.FormNumber}-invoice.pdf";

            _logger.LogInformation($"Starting create invoice PDF for form number [{model.FormNumber}]");

            var html = await this.RenderViewAsync("PDFViewSimplified", model);
            iText.Html2pdf.ConverterProperties converterProperties = new iText.Html2pdf.ConverterProperties();
            string contents = String.Empty;
            using (FileStream pdfDest = System.IO.File.Open($"{_invoicePdfPath}\\{fileName}", FileMode.Create))
            {
                iText.Html2pdf.HtmlConverter.ConvertToPdf(html, pdfDest, converterProperties);
                pdfDest.Close();
                pdfDest.Dispose();
            }

            var document = new Sentry.Domain.PaperSave.Entities.NewDocument()
            {
                FileName = fileName,
                FormNumber = model.FormNumber
            };

            using (FileStream file = System.IO.File.Open($"{_invoicePdfPath}\\{fileName}", FileMode.Open))
            {
                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    document.Contents = Convert.ToBase64String(memoryStream.ToArray());
                }
            }

            _logger.LogInformation($"Created invoice PDF for form number [{model.FormNumber}]");

            return document;
        }

        private async Task CreateFinalDocuments(long invoiceId, string formNumber)
        {
            try
            {
                _logger.LogInformation($"Starting create invoice final documents for form number [{formNumber}]");
                var finalDocument = new Sentry.Domain.PaperSave.Entities.FinalDocument()
                {
                    SystemId = invoiceId.ToString()
                };
                await _domainService.PaperSaveOperations.CreateFinalDocuments(finalDocument, formNumber);
                _logger.LogInformation($"Created final documents for form number [{formNumber}]");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating final invoice documents for form number [{formNumber}]", formNumber);
            }
        }

        private async Task CreateInvoiceCopy(string formNumber, long invoiceId)
        {
            try
            {
                _logger.LogInformation($"Starting create invoice final documents for form number [{formNumber}]");
                var finalDocument = new Sentry.Domain.PaperSave.Entities.FinalDocument()
                {
                    SystemId = invoiceId.ToString()
                };
                await _domainService.PaperSaveOperations.CreateFinalDocument(finalDocument, formNumber, $"{formNumber}-invoice.pdf");
                _logger.LogInformation($"Created invoice copy form number [{formNumber}]");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating invoice copy for form number [{formNumber}]", formNumber);
            }
        }

        [HttpPost("{invoiceId}/documents/{id}")]
        [AllowAnonymous]
        public async Task<IActionResult> AssociateFinalDocuments(long invoiceId, long id)
        {
            if (HttpContext.Request.Headers["X-API-KEY"] != _config.XAPIKey)
            {
                return Unauthorized();
            }
            try
            {
                var model = await SetupViewModel(id);
                //Create PDF copy of the form
                //We dont need to create the PDF because we already had one
                //_logger.LogInformation($"Creating PDF copy of invoice for form [{id}]");
                //var pdf = await CreatePDF(model);
                //_logger.LogInformation($"Uploading PDF copy for form [{id}]");
                //_domainService.PaperSaveOperations.UploadDocument(pdf);
                //_logger.LogInformation($"Uploaded file [{pdf.FileName}] for form [{id}]");

                //Create final documents
                _logger.LogInformation($"Creating final documents for form [{id}]");
                await CreateFinalDocuments(invoiceId, model.FormNumber);
                return Ok("documents created");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return BadRequest(ex.Message);
            }
        }

        [HttpPost("")]
        [AllowAnonymous]
        public async Task<IActionResult> CreateInvoiceAndDocuments([FromBody] InvoiceCreate form)
        {
            if (HttpContext.Request.Headers["X-API-KEY"] != _config.XAPIKey)
            {
                return Unauthorized();
            }

            _logger.LogInformation($"Starting processing form [{form.DisbursementId}]");
            var formDetails = JsonConvert.SerializeObject(form);

            try
            {
                _logger.LogInformation($"Starting create invoice and documents [{formDetails}]");

                var model = await SetupViewModel(form.DisbursementId);

                var createInvoice = new Sentry.Domain.AccountsPayable.Entities.Invoice.CreateInvoice()
                {
                    DisbursementId = form.DisbursementId,
                    PostDate = form.PostDate
                };

                //Create PDF copy of the form
                _logger.LogInformation($"Creating PDF copy of invoice for form [{formDetails}]");
                var pdf = await CreatePDF(model);

                //CREATE INVOICE
                _logger.LogInformation($"Creating invoice for form [{formDetails}]");
                var invoiceId = await _domainService.AccountsPayableOperations.CreateInvoice(createInvoice);

                //Upload PDF copy of the form
                _logger.LogInformation($"Uploading PDF copy for form [{formDetails}]");
                await _domainService.PaperSaveOperations.UploadDocument(pdf);
                _logger.LogInformation($"Uploaded file [{pdf.FileName}] for form [{formDetails}]");

                //Create final documents
                _logger.LogInformation($"Creating final documents for form [{formDetails}]");
                await CreateFinalDocuments(invoiceId, model.FormNumber);

                return Ok("Invoice and documents created");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Error processing form [{formDetails}]");
                return BadRequest($"Error processing form [{formDetails}]");
            }
        }

        [HttpPost("invoicecopy")]
        [AllowAnonymous]
        public async Task<IActionResult> CreateInvoiceCopy(InvoiceFormCreate form)
        {

Sentry.WebApp/Controllers/PDFController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Sentry.WebApp.Services;
using System.Threading.Tasks;

namespace Sentry.WebApp.Controllers
{
    public class PDFController : Controller
    {
        private readonly ILogger<PDFController> _logger;
        private readonly Config _config;
        private readonly IWebHostEnvironment _env;
        private readonly IDomainService _domainService;
        private readonly IPdfService _pdfService;

        public PDFController(ILogger<PDFController> logger,
            IOptions<Config> config,
            IWebHostEnvironment environment,
            IDomainService domainService,
            IPdfService pdfService)
        {
            _logger = logger;
            _config = config.Value;
            _env = environment;
            _domainService = domainService;
            _pdfService = pdfService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(Guid giftTransmittalId)
        {
            var md = _domainService.MasterDataWebService;
            var giftTransmittal = await _domainService.LynxWebService.LoadGiftTransmittal(giftTransmittalId);
            var pdf = _pdfService.CreateGiftTransmittalPDF(giftTransmittal, "uaf");

            //throw new NotImplementedException();
            return Ok("CREATED");
        }

    }
}

Sentry.WebApp/Views/GiftDisbursements/ReadyForProcessing.cshtml
@model Sentry.WebApp.ViewModels.GiftDisbursements.GiftDisbursementsListViewModel

@{
    ViewData["Title"] = "Ready for Processing | " + Model.Title;
}

<ul class="page-title">
    <li>
        <h1>
            @ViewData["Title"]
        </h1>
    </li>
</ul>

<ol class="breadcrumb">
    <li><a asp-area="" asp-controller="Home" asp-action="Index">Sentry Home</a></li>
    <li><a asp-area="" asp-controller="Financial" asp-action="Index">Finance Dashboard</a></li>
    <li><a asp-area="" asp-controller="GiftDisbursements" asp-action="Index">Gift Disbursements Dashboard</a></li>
    <li class="active">Record List</li>
</ol>

<div id="content-container" class="content-container table-responsive" role="main">

    <table id="ProcessTable" class="table table-hover table-striped postToGL recordList">
        <caption class="sr-only">Gift Disbursments</caption>
        <thead>
            <tr class="tableHeader">
                <th style="display: none">giftDisbursementId</th>
                <th>
                    <input type="checkbox" id="selectDisbursements" onclick="SelectAllDisbursements(this)" class="custom-control-input" />
                </th>                
                <th>Prepared By:</th>
                <th>Form Number:</th>
                <th>Payee Name:</th>
                <th>1099:</th>
                <th>Type:</th>
                <th style="display: none">Fund:</th>
                <th style="display: none">Status</th>
                <th>Instructions:</th>
                <th style="display: none">Instructions:</th>
                <th style="display: none">Reviewer Notes:</th>
                <th>Total Amount:</th>
                <th>Processing Error:</th>
                <th style="display: none">Processing Error:</th>
                <th>Date Approved:</th>
                <th style="display: none">1099 Amount:</th>               

            </tr>
        </thead>
        <tbody>
            @foreach (var giftDisbursement in Model.Disbursements)
            {
                <tr class="@(giftDisbursement.ProcessingError == null ? "" : "rejectedStatus")">
                <td style="display: none">@giftDisbursement.GiftDisbursementId</td>
                <td class="disbursementSelect">
                    <input type="checkbox" class="custom-control-input" />
                </td>
                <td>@giftDisbursement.PreparedByName</td>
                <td>@giftDisbursement.FormNumber</td>
                <td>@giftDisbursement.PayeeName</td>
                <td>@(@giftDisbursement.Has1099TotalValue ? "Yes" : "No")</td>
                <td>@giftDisbursement.PayeePaymentType</td>
                <td style="display: none">@giftDisbursement.Fund</td>
                <td style="display: none">@giftDisbursement.Rejected</td>
                <td>@giftDisbursement.PayeeSpecialInstructions</td>
                <td style="display: none">@giftDisbursement.PayeeSpecialInstructions</td>
                <td style="display: none">@giftDisbursement.ReviewerNotes</td>
                <td>@giftDisbursement.Total</td>
                <td>@giftDisbursement.ProcessingError</td>
                <td style="display: none">@giftDisbursement.ProcessingError</td>
                <td>@giftDisbursement.LastApprovedOnDate</td>
                <td style="display: none">@giftDisbursement.Total1099</td>
            </tr>
            }
        </tbody>
    </table>
    <div>
        <button type="button"
                class="btn btn-primary"
                onclick="ShowBulkProcessingModal()">
            Process All Selected
        </button>
    </div>

</div>

@await Html.PartialAsync("_BulkProcessingModal")
@await Html.PartialAsync("_PleaseWaitModal")
@await Html.PartialAsync("_BulkProcessingResultsModal")

@section scripts{
    <script>
        var bulkProcessUrl = "@Url.Action("BulkProcess", "Invoices")"; 
    </script>
    @await Html.PartialAsync("_Scripts")
}

Sentry.WebApp/Views/GiftDisbursements/Scholarships.cshtml
@model Sentry.WebApp.ViewModels.GiftDisbursements.GiftDisbursementsListViewModel

@{
    ViewData["Title"] = "Gift Disbursements for Scholarship to the University of Arizona";
}

<ul class="page-title">
    <li>
        <h1>
            @ViewData["Title"]
        </h1>
    </li>
</ul>

<ol class="breadcrumb">
    <li><a asp-area="" asp-controller="Home" asp-action="Index">Sentry Home</a></li>
    <li><a asp-area="" asp-controller="Financial" asp-action="Index">Finance Dashboard</a></li>
    <li><a asp-area="" asp-controller="GiftDisbursements" asp-action="Index">Gift Disbursements Dashboard</a></li>
    <li class="active">Record List</li>
</ol>

<div id="content-container" class="content-container table-responsive" role="main">
    @await Html.PartialAsync("_CurrentRole")

    <table id="StGiftDisbursementTable" class="table table-hover table-striped postToGL recordList">
        <caption class="sr-only">Gift Disbursments</caption>
        <thead>
            <tr class="tableHeader">
                <th style="display: none">giftDisbursementId</th>
                <th style="display: none">isPending</th>
                <th style="display: none">pendingComments</th>
                <th>Status</th>
                <th>Prepared By:</th>
                <th>Form Number:</th>
                <th>Department:</th>
                <th>Total Amount:</th>
                <th style="display: none">Reviewer Notes:</th>
                <th>Date Approved:</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var giftDisbursement in Model.Disbursements)
            {
                <tr class="@giftDisbursement.RowStatusClass">
                    <td style="display: none">@giftDisbursement.GiftDisbursementId</td>
                    <td style="display: none">@giftDisbursement.IsPending</td>
                    <td style="display: none">@giftDisbursement.PendingComments</td>
                    <td>@giftDisbursement.Rejected</td>
                    <td>@giftDisbursement.PreparedByName</td>
                    <td>@giftDisbursement.FormNumber</td>
                    <td>@giftDisbursement.DepartmentCode - @giftDisbursement.DepartmentName</td>
                    <td>@giftDisbursement.Total</td>
                    <td style="display: none">@giftDisbursement.ReviewerNotes</td>
                    <td>@giftDisbursement.LastApprovedOnDate</td>
                </tr>
            }

        </tbody>
    </table>
</div>


@section scripts{
    @await Html.PartialAsync("_Scripts")
}

Sentry.WebApp/Views/GiftDisbursements/_BulkProcessingModal.cshtml
@using System;

<div class="modal fade" id="bulkProcessingModal" tabindex="-1" role="dialog" 
     aria-labelledby="bulkProcessingModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="bulkProcessingModalLabel">Bulk Process Disbursements</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="ua-brand-x" aria-hidden="true"></i>
                </button>
            </div>
            <div class="modal-body" id="disbursements">
                <div>
                    <!--Post Date-->
                    <label class="control-label">Post Date</label>
                    <div class="input-group date">
                        <input class="form-control" id="PostDate"
                               value="@DateTime.Today.ToString("MM/dd/yyyy")" />
                        <span class="input-group-addon">
                            <i class="fas fa-calendar-alt"></i>
                        </span>
                    </div>
                </div>
                <div>
                    <h4>Disbursements to Process</h4>
                    <table id="processDisbursements" class="table mt-3">
                        <thead>
                            <tr>
                                <th style="display:none"></th>
                                <th>Form Number:</th>
                            </tr>                           
                        </thead>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link" data-dismiss="modal">Cancel</button>
                <button type="button"
                        class="btn btn-primary pull-right"
                        value="Process"
                        data-dismiss="modal"
                        onclick="BulkProcess()">
                    <i role="img" class="fas fa-check">&nbsp;</i> Process All
                </button>
            </div>
        </div>
    </div>
</div>

Sentry.WebApp/Views/GiftDisbursements/_CurrentRole.cshtml

<div>
    <p class="alert alert-info">Your current role is <b>@ViewBag.CurrentRole</b></p>
</div>

Sentry.WebApp/Views/GiftDisbursements/_EMTransferTo.cshtml
@model Sentry.WebApp.ViewModels.GiftDisbursements.GiftDisbursementsViewModel

<input type="hidden" asp-for="DisbursementTo.Payee.PayeeIs" value=" @Model.DisbursementTo.Payee.PayeeIs" />
<input type="hidden" asp-for="DisbursementTo.Payee.PayeeName" value="@Model.DisbursementTo.Payee.PayeeName" />
<input type="hidden" asp-for="DisbursementTo.Payee.PayeeAddress1" value="@Model.DisbursementTo.Payee.PayeeAddress1" />
<input type="hidden" asp-for="DisbursementTo.Payee.PayeeCity" value="@Model.DisbursementTo.Payee.PayeeCity" />
<input type="hidden" asp-for="DisbursementTo.Payee.PayeeState" value="@Model.DisbursementTo.Payee.PayeeState" />
<input type="hidden" asp-for="DisbursementTo.Payee.PayeeZip" value="@Model.DisbursementTo.Payee.PayeeZip" />
<input type="hidden" asp-for="DisbursementTo.Payee.PayeePaymentType" value="@Model.DisbursementTo.Payee.PayeePaymentType" />
<input type="hidden" asp-for="DisbursementTo.Payee.PayeeSpecialInstructions" value="@Model.DisbursementTo.Payee.PayeeSpecialInstructions" />

<dl class="dl-horizontal">
    <dt>UA Employee:</dt>
    <dd>@Model.DisbursementTo.Payee.UAEmployee</dd>
    <dt>Payee Name:</dt>
    <dd>@Model.DisbursementTo.Payee.PayeeName</dd>
    <dt>Address:</dt>
    <dd>
        @Model.DisbursementTo.Payee.PayeeAddress1<br />
        @Model.DisbursementTo.Payee.PayeeCity, @Model.DisbursementTo.Payee.PayeeState @Model.DisbursementTo.Payee.PayeeZip
    </dd>
    <dt>Payee Payment Type:</dt>
    <dd>@Model.DisbursementTo.Payee.PayeePaymentType</dd>
    <dt>Special Instructions:</dt>
    <dd>@Model.DisbursementTo.Payee.PayeeSpecialInstructions</dd>
    <dt>W-9 Year</dt>
    <dd>@Model.DisbursementTo.Payee.PayeeW9Year</dd>
    <dt>
        ICA Year 
        @if (Model.DisbursementTo.Payee.PayeeICAYearExpired)
        {
            <span id="ICAYearExpired" class="badge badge-red" title="Vendor's ICA has expired or is not on file">
                Expired
            </span>
        }
    </dt>
    <dd>@Model.DisbursementTo.Payee.PayeeICAYear </dd>
</dl>






Sentry.WebApp/Views/GiftDisbursements/_KFSNumberModal.cshtml
<div class="modal fade" id="kfsNumberModal" tabindex="-1" role="dialog" aria-labelledby="kfsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="kfsNumberModalLabel">KFS Account Starts With</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="ua-brand-x" aria-hidden="true"></i>
                </button>
            </div>
            <div class="modal-body" id="kfsNumberModal">
                <p id="KfsNumber" style="word-wrap:normal"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-blue" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

Sentry.WebApp/Views/GiftDisbursements/_PendingCommentsModal.cshtml
<div class="modal fade" id="PendingCommentsModal" tabindex="-1" role="dialog" aria-labelledby="CommentsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="CommentsModalLabel">Pending Comments</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="ua-brand-x" aria-hidden="true"></i>
                </button>
            </div>
            <div class="modal-body" id="PendingComments">
                <p id="PendingCommentsText" style="word-wrap:normal"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-blue" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>