Sentry.WebApp/ViewModels/GiftTransmittal/GiftTransmittalListViewModel.cs
using System;
using System.Collections.Generic;

namespace Sentry.WebApp.ViewModels.GiftTransmittal
{
    public class GiftTransmittalListItem
    {

        public Guid Id { get; set; }
        public Guid ItemId { get; set; }
        public string DateCreated { get; set; }
        public string FormNumber { get; set; }
        //public string FormState { get; set; }
        public string Constituent { get; set; }
        public string Total { get; set; }
        public string BatchType { get; set; }
        public string PreparedBy { get; set; }
        public bool WaitingOnResponseFromBursar { get; set; }
        public bool WaitingOnResponseFromPreparer { get; set; }
        public string Status { get; set; }
        public int CurrentApprovalStage { get; set; }
        public string SecondaryApproverStatus { get; set; }
        public string PostDate { get; set; }
        public bool HasProcessingError { get; set; }

        public static explicit operator GiftTransmittalListItem(Sentry.Domain.Lynx.DataAccess.Entities.GiftTransmittal.GiftTransmittal giftTransmittal)
        {
            if (giftTransmittal.ItemId != null)
            {
                return new GiftTransmittalListItem()
                {
                    Id = new Guid(giftTransmittal.Id),
                    ItemId = new Guid(giftTransmittal.ItemId),
                    DateCreated = giftTransmittal.DateAdded.ToString("MM/dd/yyyy"),
                    FormNumber = giftTransmittal.FormNumber,
                    BatchType = giftTransmittal.BatchType,
                    PreparedBy = $"{giftTransmittal.PreparedByFirstName} {giftTransmittal.PreparedByLastName}",
                    //FormState = giftTransmittal.Status,
                    Constituent = String.IsNullOrWhiteSpace(giftTransmittal.ConstituentOrganizationName) ? giftTransmittal.ConstituentName : giftTransmittal.ConstituentOrganizationName,
                    Total = giftTransmittal.Amount.ToString("C"),
                    WaitingOnResponseFromBursar = giftTransmittal.WaitingOnResponseFromBursar,
                    WaitingOnResponseFromPreparer = giftTransmittal.WaitingOnResponseFromPreparer,
                    Status = giftTransmittal.Status,
                    CurrentApprovalStage = giftTransmittal.CurrentApprovalStage,
                    SecondaryApproverStatus = giftTransmittal.SecondaryApprovalStatus,
                    PostDate = giftTransmittal.PostDate.ToString("MM/dd/yyyy"),
                    HasProcessingError = giftTransmittal.HasProcessingError
                };
            }
            else
            {
                //This is a bad gift transmittal. does not have any items. cant be edited.
                //TODO cleanup?
                return new GiftTransmittalListItem()
                {
                    Id = new Guid(giftTransmittal.Id),
                    ItemId = Guid.Empty,
                    DateCreated = giftTransmittal.DateAdded.ToString("MM/dd/yyyy"),
                    FormNumber = giftTransmittal.FormNumber,
                    BatchType = giftTransmittal.BatchType,
                    PreparedBy = giftTransmittal.PreparedBy,
                    //FormState = "ERROR",
                    Constituent = "ERROR",
                    Total = "ERROR",
                };
            }
        }
    }
    public class GiftTransmittalListViewModel : BaseIntegrationViewModel
    {
        public GiftTransmittalListViewModel() : base() { }
        public string Organization { get; set; }        
        public IEnumerable<GiftTransmittalListItem> GiftTransmittals { get; set; }
        public bool DisplayRequiringPhysicalDocuments { get; set; } = false;
        public string ListType { get; set; }
    }
}

Sentry.WebApp/Controllers/GiftTransmittalController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Sentry.WebApp.ViewModels;
using Sentry.WebApp.Data;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Configuration;
using Sentry.WebApp.Services;
using Sentry.WebApp.ViewModels.GiftTransmittal;
using System.IO;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using Sentry.WebApp.ViewModels.SupportingDocuments;
using Sentry.WebApp.Data.Models.Notifications;
using Microsoft.Extensions.Options;
using Sentry.WebApp.ViewModels.GiftDisbursements;
using Sentry.Domain.Lynx.DataAccess.Entities.GiftTransmittal;
using Sentry.Domain.AccountsReceivable;
using Sentry.Domain.AccountsReceivable.Entities;
using Sentry.Domain.PaperSave.Entities;
using Sentry.Domain.Lynx.Entities.WebService.GiftTransmittal;
using Sentry.WebApp.Data.Models.GiftTransmittal;
using Sentry.Domain.CentralizedAccessManagement.Entities;
using System.Globalization;
using static iText.StyledXmlParser.Jsoup.Select.Evaluator;
using Sentry.WebApp.Extensions;
using Sentry.WebApp.WebConstants;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Hosting;

namespace Sentry.WebApp.Controllers
{
    public class GiftTransmittalController : IntegrationController
    {
        //private readonly IDomainService _domainService;
        public readonly Config _config;
        private readonly INotificationService _notificationService;
        private readonly AccountsReceivableOperations _arOperations;
        private readonly IPdfService _pdfService;
        private readonly IWebHostEnvironment _environment;
        private readonly string _bursarPdfPath;

        public GiftTransmittalController(AppDbContext context,
            DwDbContext dwContext,
            ILogger<GiftTransmittalController> logger,
            IConfiguration configuration,
            IDomainService domainService,
            IOptions<Config> config,
            INotificationService notificationService,
            IPdfService pdfService,
            IWebHostEnvironment environment)
            : base(context, dwContext, logger, configuration, domainService)
        {
            _config = config.Value;
            _notificationService = notificationService;
            _arOperations = domainService.AccountsReceivableOperations;
            _pdfService = pdfService;
            _environment = environment;
            _bursarPdfPath = $"{environment.WebRootPath}\\bursar-pdfs";
        }

        private ModelHelper Helper
        {
            get
            {
                return new ModelHelper(HttpContext);
            }
        }

        //public async Task<IActionResult> BursarPDFView()
        //{
        //    var giftTransmittalId = new Guid("bdcb745f-1430-458c-a703-260454dd413b");
        //    var giftTransmittalItemId = new Guid("5abb8579-2426-4761-8f0c-80cd9d6af926");

        //    var giftTransmittal = await _domainService.LynxWebService.LoadGiftTransmittal(giftTransmittalId);
        //    //when we map it to the view model using the details of the gift transmittal item that matches the giftTransmittalItemId
        //    var giftTransmittalItem = giftTransmittal.GiftTransmittalItems.Where(i => i.Id == giftTransmittalItemId).First();
        //    var distributions = giftTransmittalItem.GiftTransmittalItemDistributions.Where(d => !d.IsDeleted).Select(d => (Distribution)d).ToList();

        //    var organization = giftTransmittal.FormNumber.StartsWith("GT") ? "UAF" : "UA";
        //    foreach (var distribution in distributions)
        //    {
        //        var designation = await _domainService.MasterDataWebService.GetDesignation(organization, distribution.FundAccount);
        //        distribution.Designation = designation.Name;
        //    }

        //    var model = new BursarPDF()
        //    {
        //        FormNumber = giftTransmittal.FormNumber,
        //        CheckNumber = giftTransmittalItem.CheckNumber,
        //        Distributions = distributions,
        //        PreparedBy = new PreparedBy()
        //        {
        //            ContactName = giftTransmittal.ContactName
        //        }
        //    };

        //    return View(model);
        //}

        public IActionResult GTForms(bool displayRequiringPhysicalDocuments = false)
        {
            var giftTransmittals = Enumerable.Empty<Sentry.Domain.Lynx.DataAccess.Entities.GiftTransmittal.GiftTransmittal>();
            if (Helper.IsGTRole)
            {
                giftTransmittals = _domainService.LynxDataOperations.GetGiftTransmittals(!displayRequiringPhysicalDocuments)
                    .Where(t => t.FormNumber.StartsWith("GT"))
                    .Where(t => t.Status != "Initialized")
                    .Where(t => t.WaitingOnResponseFromBursar != true)
                    .Where(t => t.WaitingOnResponseFromPreparer != true)
                    .Where(t => t.CurrentApprovalStage == 1);
            }

            var listType = "GTForms";
            var model = GiftTransmittalStatusPageSetup(listType);
            model.GiftTransmittals = giftTransmittals.Select(g => (GiftTransmittalListItem)g);
            model.DisplayRequiringPhysicalDocuments = displayRequiringPhysicalDocuments;

            return View("List", model);
        }

        #region Status Lists

        public IActionResult WaitingOnBursarForms(bool displayRequiringPhysicalDocuments = false)
        {
            var giftTransmittals = Enumerable.Empty<Sentry.Domain.Lynx.DataAccess.Entities.GiftTransmittal.GiftTransmittal>();
            if (Helper.IsGTRole)
            {
                giftTransmittals = _domainService.LynxDataOperations.GetGiftTransmittals(!displayRequiringPhysicalDocuments)
                    .Where(t => t.WaitingOnResponseFromBursar == true);
            }

            var listType = "WaitingOnBursarForms";
            var model = GiftTransmittalStatusPageSetup(listType);
            model.GiftTransmittals = giftTransmittals.Select(g => (GiftTransmittalListItem)g);
            model.DisplayRequiringPhysicalDocuments = displayRequiringPhysicalDocuments;
            model.ListType = listType;

            return View("StatusList", model);
        }

        public IActionResult WaitingOnPreparerForms(bool displayRequiringPhysicalDocuments = false)
        {
            var giftTransmittals = Enumerable.Empty<Sentry.Domain.Lynx.DataAccess.Entities.GiftTransmittal.GiftTransmittal>();
            if (Helper.IsGTRole)
            {
                giftTransmittals = _domainService.LynxDataOperations.GetGiftTransmittals(!displayRequiringPhysicalDocuments)
                .Where(t => t.WaitingOnResponseFromPreparer == true);
            }

            var listType = "WaitingOnPreparerForms";
            var model = GiftTransmittalStatusPageSetup(listType);
            model.GiftTransmittals = giftTransmittals.Select(g => (GiftTransmittalListItem)g);
            model.DisplayRequiringPhysicalDocuments = displayRequiringPhysicalDocuments;
            model.ListType = listType;

            return View("StatusList", model);
        }
        #endregion

        public IActionResult GUForms(bool displayRequiringPhysicalDocuments = false)
        {
            var giftTransmittals = Enumerable.Empty<Sentry.Domain.Lynx.DataAccess.Entities.GiftTransmittal.GiftTransmittal>();
            if (Helper.IsGURole)
            {
                giftTransmittals = _domainService.LynxDataOperations.GetGiftTransmittals(!displayRequiringPhysicalDocuments)
                    .Where(t => t.FormNumber.StartsWith("GU"))
                    .Where(t => t.Status != "Initialized")
                    .Where(t => t.WaitingOnResponseFromBursar != true)
                    .Where(t => t.WaitingOnResponseFromPreparer != true)
                    .Where(t => t.CurrentApprovalStage == 1);
            }
            var listType = "GUForms";
            var model = GiftTransmittalStatusPageSetup(listType);
            model.GiftTransmittals = giftTransmittals.Select(g => (GiftTransmittalListItem)g);
            model.DisplayRequiringPhysicalDocuments = displayRequiringPhysicalDocuments;

            return View("List", model);
        }
        public IActionResult InitializedForms()
        {
            var giftTransmittals = _domainService.LynxDataOperations.GetGiftTransmittals(true)
                .Where(t => t.Status == "Initialized");

            var listType = "InitializedForms";
            var model = GiftTransmittalStatusPageSetup(listType);
            model.GiftTransmittals = giftTransmittals.Select(g => (GiftTransmittalListItem)g);
            model.DisplayRequiringPhysicalDocuments = true;

            return View("InitializedList", model);
        }

        public IActionResult SecondaryApproverForms(bool displayRequiringPhysicalDocuments = false)
        {
            var listType = "SecondaryApproverForms";
            var model = GiftTransmittalStatusPageSetup(listType);
            model.DisplayRequiringPhysicalDocuments = displayRequiringPhysicalDocuments;
            if (Helper.IsARSecondaryReviewer)
            {
                var giftTransmittals = _domainService.LynxDataOperations.GetGiftTransmittals(!displayRequiringPhysicalDocuments);
                model.GiftTransmittals = giftTransmittals.Select(g => (GiftTransmittalListItem)g)
                    .Where(g => g.CurrentApprovalStage == 2);
            }
            else
            {
                model.GiftTransmittals = Enumerable.Empty<GiftTransmittalListItem>();
            }

            return View("List", model);
        }


Sentry.WebApp/Views/GiftTransmittal/Index.cshtml
@model Sentry.WebApp.ViewModels.BaseViewModel

<ul class="page-title">
    <li>
        <h1>
            Welcome to Your @Model.Title Dashboard
        </h1>
    </li>
</ul>

<div id="content-container" class="content-container" role="main">
    <div class="row">
        <div class="col-sm-12">
            @*<p class="lead">Welcome to your @Model.Title Dashboard!</p>*@
            <p>Here is where you'll remediate any @Model.Title records which have failed the business' validation rules in the Data Integration Framework<sup>&#174;</sup><sup>&trade;</sup></p>
            <p>The @Model.Title Integration is made up of several smaller integrations as indicated by the sub-menu items listed below the @Model.Title heading.</p>
            <p>Select one of the smaller Integrations on the left to begin the remediation process.</p>
            
        </div>
    </div><!-- /.row -->

    <div class="row">
        <div class="col-sm-12">
            <a href="/GiftTransmittal/Create?organization=uaf">Initialize Gift Transmittal for the University of Arizona Foundation</a>
        </div>
        <div class="col-sm-12">
            <a href="/GiftTransmittal/Create?organization=ua">Initialize Gift Transmittal for the University of Arizona</a>
        </div>
    </div><!-- /.row -->
    <div class="row">
        <div class="col-md-4 form-group mt-2">
            <label class="control-label" for="TransmittalSearchInput">Search</label>
            <br />
            <div class="d-inline-flex">
                <input id="TransmittalSearchInput" type="text" class="form-control" placeholder="Search by Form Number" />
                <button type="button" class="btn btn-primary ml-3" id="TransmittalSearchButton" title="Search Transmittal"><i role="img" class="fas fa-search"></i></button>
            </div>
            <p id="TransmittalSearchMessage" class="text-danger"></p>
        </div>
    </div>
</div><!-- /.content-container -->
@section scripts {
    <script>
        $(document).ready(function () {


            // Color Variables
            const colors = {
                primaryBlue: '#0C234B',
                primarySkyBlue: '#81D3EB',
                primaryOasisBlue: '#378DBD',
                primaryAzuriteBlue: '#1E5288',
                primaryMidnightBlue: '#001C48',

                primaryRed: '#AB0520',
                primaryRedBloom: '#EF4056',
                primaryRedChili: '#8B0015',

                neutralCoolGray: '#E2E9EB',
                neutralWarmGray: '#F4EDE5',

                secondaryLeaf: '#70B865',
                secondaryRiver: '#007D84',
                secondarySilver: '#9EABAE',
                secondaryMesa: '#a95c42',

                legacyDarkSilver: '#49595E',
            };

        });
    </script>
    <script>
        $('#TransmittalSearchButton').click(function (e) {
            var formNumber = $('#TransmittalSearchInput').val();

            if (formNumber != undefined && formNumber.length > 0) {
                SearchByFormNumber(formNumber);
            }
        });

        function SearchByFormNumber(formNumber) {
            $('#TransmittalSearchMessage').text(null);

            $.ajax({
                type: "GET",
                url: '@Url.Action("GetGiftTransmittalByFormNumber")',
                data: { formNumber: formNumber },
                headers:
                {
                    "RequestVerificationToken": $('input:hidden[name="__RequestVerificationToken"]').val()
                },
                success: function (data) {
                    if (data.id != "00000000-0000-0000-0000-000000000000" &&
                        data.giftTransmittalItems != undefined && data.giftTransmittalItems.length > 0) {
                        var url = `@Url.Action("Edit", "GiftTransmittal")?giftTransmittalId=${data.id}&giftTransmittalItemId=${data.giftTransmittalItems[0].id}`;
                        window.location.href = url;
                    }
                    else {
                        $('#TransmittalSearchMessage').text('No Results')
                    }
                },
                error: function (request, error) {
                    $('#TransmittalSearchMessage').text('No Results');
                }
            });
        }
    </script>
}

Sentry.WebApp/Views/GiftTransmittal/InitializedList.cshtml
@model Sentry.WebApp.ViewModels.GiftTransmittal.GiftTransmittalListViewModel
@{
    ViewData["Title"] = Model.Title;
}

<ul class="page-title">
    <li>
        <h1>
            Initialized Gift Transmittals
        </h1>
    </li>
</ul>

<ol class="breadcrumb">
    <li><a asp-area="" asp-controller="Home" asp-action="Index">Sentry Home</a></li>
    <li><a asp-area="" asp-controller="Financial" asp-action="Index">Finance Dashboard</a></li>
    <li><a asp-area="" asp-controller="GiftTransmittal" asp-action="Index">Gift GiftTransmittal Dashboard</a></li>
    <li class="active">Record List</li>
</ol>

<div id="content-container" class="content-container" role="main">
    <div class="table-responsive">
        
        <table id="initializedGiftTransmittalTable" class="table table-hover table-striped postToGL recordList">
            <caption class="sr-only">Initialized Gift Transmittals</caption>
            <thead>
                <tr class="tableHeader">
                    <th style="visibility: collapse">Id</th>
                    <th style="visibility: collapse">Item Id</th>
                    <th>Form Number:</th>
                    <th>Transaction Type:</th>
                    <th>Prepared By:</th>
                    <th>Constituent:</th>
                    <th>Total:</th>
                    <th>Date Created:</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var giftTransmittal in Model.GiftTransmittals)
                {
                    <tr>
                        <td style="visibility: collapse">@giftTransmittal.Id</td>
                        <td style="visibility: collapse">@giftTransmittal.ItemId</td>
                        <td>@giftTransmittal.FormNumber</td>
                        <td>@giftTransmittal.BatchType</td>
                        <td>@giftTransmittal.PreparedBy</td>
                        <td>@giftTransmittal.Constituent</td>
                        <td>@giftTransmittal.Total</td>
                        <td>@giftTransmittal.DateCreated</td>                       
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>


@section scripts{
    @await Html.PartialAsync("_Scripts")
}



Sentry.WebApp/Views/GiftTransmittal/List.cshtml
@model Sentry.WebApp.ViewModels.GiftTransmittal.GiftTransmittalListViewModel
@{
    ViewData["Title"] = Model.Title;
}

<ul class="page-title">
    <li>
        <h1>
            @ViewData["Title"]
        </h1>
    </li>
</ul>

<ol class="breadcrumb">
    <li><a asp-area="" asp-controller="Home" asp-action="Index">Sentry Home</a></li>
    <li><a asp-area="" asp-controller="Financial" asp-action="Index">Finance Dashboard</a></li>
    <li><a asp-area="" asp-controller="GiftTransmittal" asp-action="Index">Gift GiftTransmittal Dashboard</a></li>
    <li class="active">Record List</li>
</ol>

<div id="content-container" class="content-container" role="main">
    <div class="table-responsive">        
        <div>
            @if (Model.DisplayRequiringPhysicalDocuments)
            {
                <a href="/GiftTransmittal/@Model.ListType?displayRequiringPhysicalDocuments=false">Display all forms ready for processing</a>
            }
            else
            {
                <a href="/GiftTransmittal/@Model.ListType?displayRequiringPhysicalDocuments=true">Display forms awaiting physical documents</a>
            }
        </div>
        <table id="giftTransmittalTable" class="table table-hover table-striped postToGL recordList">
            <caption class="sr-only">@ViewData["Title"]</caption>
            <thead>
                <tr class="tableHeader">
                    <th style="visibility: collapse">Id</th>
                    <th style="visibility: collapse">Item Id</th>
                    <th style="visibility: collapse">Waiting on Response from Bursar</th>
                    <th style="visibility: collapse">Waiting on Response from Preparer</th>
                    <th style="visibility: collapse">Status</th>
                    <th style="visibility: collapse">Secondary Approver Status</th>
                    <th title="Status">Status</th>
                    <th>Form Number:</th>
                    <th>Transaction  Type:</th>
                    <th>Prepared By:</th>
                    <th>Constituent:</th>
                    <th>Total:</th>
                    <th>Processing Error:</th>
                    <th>Date Created:</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var giftTransmittal in Model.GiftTransmittals)
                {
                    <tr class="@(giftTransmittal.SecondaryApproverStatus == "Rejected" ? "rejectedStatus" : "") 
                               @(giftTransmittal.HasProcessingError == true ? "rejectedStatus" : "")">
                        <td style="visibility: collapse">@giftTransmittal.Id</td>
                        <td style="visibility: collapse">@giftTransmittal.ItemId</td>
                        <td style="visibility: collapse">@giftTransmittal.WaitingOnResponseFromBursar</td>
                        <td style="visibility: collapse">@giftTransmittal.WaitingOnResponseFromPreparer</td>
                        <td style="visibility: collapse">@giftTransmittal.SecondaryApproverStatus</td>
                        <td style="visibility: collapse">@giftTransmittal.Status</td>
                        <td>@giftTransmittal.WaitingOnResponseFromBursar</td>
                        <td>@giftTransmittal.FormNumber</td>
                        <td>@giftTransmittal.BatchType</td>
                        <td>@giftTransmittal.PreparedBy</td>
                        <td>@giftTransmittal.Constituent</td>
                        <td>@giftTransmittal.Total</td>
                        <td>@(@giftTransmittal.HasProcessingError ? "Yes": "No")</td>
                        <td>@giftTransmittal.DateCreated</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>


@section scripts{
    @await Html.PartialAsync("_Scripts")
}



Sentry.WebApp/Views/GiftTransmittal/StatusList.cshtml
@model Sentry.WebApp.ViewModels.GiftTransmittal.GiftTransmittalListViewModel
@{
    ViewData["Title"] = Model.Title;
}

<ul class="page-title">
    <li>
        <h1>
            @ViewData["Title"]
        </h1>
    </li>
</ul>

<ol class="breadcrumb">
    <li><a asp-area="" asp-controller="Home" asp-action="Index">Sentry Home</a></li>
    <li><a asp-area="" asp-controller="Financial" asp-action="Index">Finance Dashboard</a></li>
    <li><a asp-area="" asp-controller="GiftTransmittal" asp-action="Index">Gift Transmittal Dashboard</a></li>
    <li class="active">Record List</li>
</ol>

<div id="content-container" class="content-container" role="main">
    <div class="table-responsive">  
        <div>
            @if (Model.DisplayRequiringPhysicalDocuments)
            {
                <a href="/GiftTransmittal/@Model.ListType?displayRequiringPhysicalDocuments=false">Display all forms ready for processing</a>
            }
            else
            {
                <a href="/GiftTransmittal/@Model.ListType?displayRequiringPhysicalDocuments=true">Display forms awaiting physical documents</a>
            }
        </div>
        <table id="giftTransmittalStatusTable" class="table table-hover table-striped postToGL recordList">
            <caption class="sr-only">Gift Transmittals</caption>
            <thead>
                <tr class="tableHeader">
                    <th style="visibility: collapse">Id</th>
                    <th style="visibility: collapse">Item Id</th>
                    <th>Form Number:</th>
                    <th>Transaction  Type:</th>
                    <th>Prepared By:</th>
                    <th>Constituent:</th>
                    <th>Total:</th>
                    <th>Date Created:</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var giftTransmittal in Model.GiftTransmittals)
                {
                    <tr>
                        <td style="visibility: collapse">@giftTransmittal.Id</td>
                        <td style="visibility: collapse">@giftTransmittal.ItemId</td>
                        <td>@giftTransmittal.FormNumber</td>
                        <td>@giftTransmittal.BatchType</td>
                        <td>@giftTransmittal.PreparedBy</td>
                        <td>@giftTransmittal.Constituent</td>
                        <td>@giftTransmittal.Total</td>
                        <td>@giftTransmittal.DateCreated</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>


@section scripts{
    @await Html.PartialAsync("_Scripts")
}



Sentry.WebApp/Views/GiftTransmittal/_Scripts.cshtml
@using Sentry.WebApp.ViewModels;
@{
    var modelHelper = new ModelHelper(Context);
}

<script type="text/javascript" src="@Url.Content($"~/js/GiftTransmittal.js?version={modelHelper.Version}")"></script>
<script>
    var Organization = '@Model.Organization';
    var GetGiftTransmittalsURL = '@Url.Action("Edit", "GiftTransmittal")';
    var createGiftTransmittalURL = '@Url.Action("Create")';
    var PreparerDetailsURL = '@Url.Action("GetEmployeesByEmployeeId", "GiftTransmittal")';
    var getCollegesURL = '@Url.Action("GetColleges")';
    var getDepartmentsURL = '@Url.Action("GetDepartments")';
    var getProjectsURL = '@Url.Action("GetProjects")';
    var SearchProjectURL = '@Url.Action("SearchProject")';
    var deleteDistributionURL = '@Url.Action("DeleteDistribution")'
    var uploadSupportingDocumentURL = '@Url.Action("UploadSupportingDocument")';
    var deleteSupportingDocumentURL = '@Url.Action("DeleteSupportingDocument")';
    var getSupportingDocumentsURL = "@Url.Action("GetSupportingDocuments")";
    var viewSupportingDocumentURL = "@Url.Action("ViewSupportingDocument")";
</script>